# Generated by Django 5.1.6 on 2025-02-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discount_product_is_discount_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
